"""Add status column to ShiftAssignment table

Revision ID: 30133ab6b50d
Revises: 
Create Date: 2024-11-01 12:03:37.378937

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "30133ab6b50d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift_assignment", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.String(length=50),
                nullable=False,
                server_default="Available",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("shift_assignment", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
